### ISSUE TITLE
mapbox upload set name from filename rather than tileset id

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-cli-py#106]
`mapbox upload user.tilesetid file.geojson`

without the `--name` option I think it's better to use `file` as the Tileset name rather than the current `tilesetid`. `tilesetid` is usually a random string and defaulting to `file` seems to make more sense.

**Comment by perrygeo** [comment]
@andrewharvey The CLI was designed specifically to use `TILESET` as the basis for naming, based on the feedback that keeping tileset *name* and *id* consistent was a high priority for our users. 

Keeping tileset names consistent with the *original filenames* is certainly possible with some scripting. But it's not a goal of this project or a high priority for most use cases.

Because current users rely on the behavior of extracting the `name` from the `TILESET`, implement ing this change would breaking existing scripts. I'm inclined to keep the existing behavior as a result.
