### ISSUE TITLE
Validation strategy

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-cli-py#20]
A general design question: What is our strategy for dealing with validation of input parameters?

The way it works now is
* some known bad parameters are caught by the SDK and raise a python exception (the stacktrace is a bit intimidating and exposes the python underbelly to the CLI world)
* other bad parameters are passed through to the API and the error message is conveyed (actually much cleaner errors, for example the static map size error in #19  returns `Error: {"message":"Height must be between 1-1280."}`) This puts a burden on the API when we could easily catch it before we hit the request.

I'm thinking the best approach is:
1. do as much validation as possible in the SDK and raise a consistent exception type (ValueError seems too general)
2. catch that exception at the CLI and re-raise using either a [`click.UsageError`](http://click.pocoo.org/5/api/#click.UsageError) or a [`click.BadParameter`](http://click.pocoo.org/5/api/#click.BadParameter)

Alternatively, we could do all the validation at the CLI end and let the Python SDK play fast and loose, relying on the API response.

Doing the validation in both spots seems like a bad plan.

/cc @sgillies

**Comment by perrygeo** [comment]
Per chat w @sgillies:
* Write validation logic in SDK
* Write click callbacks in CLI (which leverage the validation logic in the SDK)
* Simple functions instead of stateful methods (keep it testable)

I'm still stuck on exactly how the implementation is going to look, it could take one of several forms but I'm currently leaning towards:

* `mapbox.validate` module exposing a bunch of functions with the signature `f(val) -> val`
* `mapboxcli.validate` module with a bunch of wrapper functions that call ^ and reraise `click.BadParameter`. These would be click callbacks and take the signature `f(ctx, param, val) -> val`

The validation modules could even handle the geojson feature validation and normalization.

**Comment by perrygeo** [comment]
@sgillies, I created `validation` branches in both the sdk and cli. Started off with geocoding, let's review this before I go ahead with the other services:

In the CLI:
https://github.com/mapbox/mapbox-cli-py/commit/957694d913551a0ecc7ba121c4794681631ea101

In the SDK:
https://github.com/mapbox/mapbox-sdk-py/commit/b23500327f1eb9661bfcba69279eda8032941e2e

**Comment by sgillies** [comment]
Agreed that we shouldn't repeat ourselves. How about this (a restatement of our conclusions from yesterday plus some new thoughts):

## SDK

- In the SDK we are committed to preventing requests that will fail :100: because of invalid arguments (image sizes, travel modes, geocoding datasets)
- Let's validate them using functions in a `validation` module, not with in-line code.
- Raise SDK-specific exceptions that derive from `ValueError` (or `KeyError` for, say, travel modes).

## CLI

- We're committed :100: to sparing CLI users from reading tracebacks.
- The CLI takes responsibility for validating: input/output file paths and the few other things that aren't a concern of the SDK
- Otherwise, rely on the SDK, re-raising its errors as you suggest above.
- We could reserve the option to write validiating Click callbacks using methods from the SDK's validation module if we have a future need.

**Comment by perrygeo** [comment]
:+1: I'll work on implementing this soon.

> rely on the SDK, re-raising its errors ...
> write validiating Click callbacks using methods from the SDK's validation module if we have a future need

I realized that writing click callbacks means testing everything twice (once on arg parsing, once when you run it). I think just catching SDK exceptions is sufficient and DRY.
