### ISSUE TITLE
Try cx_freeze for packaging CLI program

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-cli-py#45]
I'm not sure if this is the way to go, but I've been curious about cx_freeze.

See also #18.

**Comment by sgillies** [comment]
It appears that our use of setuptools' pkg_resources is incompatible with cx_freeze. We'd need to change the program design to use cx_freeze.

**Comment by perrygeo** [comment]
There's also [pyinstaller](http://www.pyinstaller.org/) and bbfreeze](https://github.com/schmir/bbfreeze) (unmaintained) both of which can theoretically create cross-platform binaries.

There are some other options out there but they all seem to be platform specific:

* [py2exe](http://www.py2exe.org/) for win
* [py2app](https://pythonhosted.org/py2app/) for os x
* [exxe](https://github.com/mbachry/exxo/) for x64 linux

There's also the perhaps insane idea of supporting [Jython](http://www.jython.org/) or [zippy](https://bitbucket.org/ssllab/zippy) and packaging it as a jar file to run on the JVM. :dizzy_face:

**Comment by perrygeo** [comment]
`pyinstaller` looks active and promising but it looks like it doesn't support console_scripts in setup.py

**Comment by perrygeo** [comment]
Update on `pyinstaller`: It works, sorta. Instead of using `click_plugins.with_plugins` to dynamically pull the subcommands from the entry points, you can explictly define subcommand as part of a group

```diff
+from .cli  import main_group

-@click.command(short_help="Geocode an address or coordinates.")
+@main_group.command(short_help="Geocode an address or coordinates.")
```

write the main `cli.py` as a wrapper script to do explicit imports

```
from mapboxcli.scripts.geocoding import geocoding

if __name__ == "__main__":
    main_group()
```

then run pyinstaller on the wrapper script to produce an executable

```
$ file dist/mapbox/mapbox
mapbox: Mach-O 64-bit executable x86_64
```
and geocoding works as expected. 

Implications of this approach? Compiled script means no dynamic plugins at runtime, lose the ability to do user plugins.

**Comment by sgillies** [comment]
Too old. I don't think we're going to go this route.
