### ISSUE TITLE
Possible mapbox cli bug?

### ISSUE THREAD

**Issue by JayBrown** [mapbox/mapbox-cli-py#72]
In closed issues I've found similar reports, but it seems that subsequent updates—I'm using v0.3.1—haven't dealt with the problem. I'm occasionally getting error messages (see screenshot below); in this case mapbox-cli-py is part of a shell script that runs within BitBar.

![mapbox_error](https://cloud.githubusercontent.com/assets/477431/15711095/ed27f416-280c-11e6-995f-ed0c818c5a04.png)

**Comment by perrygeo** [comment]
@JayBrown what are the input parameters that cause the error?

**Comment by JayBrown** [comment]
It's one of those three:
https://github.com/JayBrown/VBBar/blob/master/VBBar.30m.sh#L402
https://github.com/JayBrown/VBBar/blob/master/VBBar.30m.sh#L512
https://github.com/JayBrown/VBBar/blob/master/VBBar.30m.sh#L530

**Comment by perrygeo** [comment]
Have you confirmed that CURRENT_LAT and CURRENT_LONG are valid numbers? It looks like your script needs to guard against invalid locations, i.e. accounting for https://github.com/JayBrown/VBBar/blob/master/VBBar.30m.sh#L373-L374

**Comment by perrygeo** [comment]
I can reproduce the error using the following in valid command:

```
$ mapbox geocoding --reverse "[ , ]" -t address
```

A ValueError is the expected behavior since the `--reverse` argument needs to be a valid array with two numeric (float) coordinates. Your script should guard against this condition and avoid making a call to the mapbox API unless you have a valid lat and lon.

What behavior would you suggest in this case?

**Comment by JayBrown** [comment]
Thank you. I just included another condition for the mapbox query. Hope it'll work.
